### ISSUE TITLE
Input to `.fit()` should have rank 4.

### ISSUE THREAD

**Issue by tegillis** [Aaronphilip2/Image-Segmentation-for-Faces#2]
When running `mask_datagen.fit(np.expand_dims(np.expand_dims(np.asarray(Image.open(mask_path)), axis=0), axis=4), augment=True, seed=seed)`, I'm getting this error:
```
  File "train_model.py", line 50, in <module>
    train_generator = utils.image_generator(img_path, label_path, img_dir_path, label_dir_path)
  File "/home/tgillis/celeb_gan/Image-Segmentation-On-Faces/utils/run_utils.py", line 27, in image_generator
    mask_datagen.fit(np.expand_dims(np.expand_dims(np.asarray(Image.open(mask_path)), axis=0), axis=4), augment=True, seed=seed)
  File "/home/tgillis/anaconda3/envs/stargan/lib/python3.6/site-packages/keras_preprocessing/image.py", line 1347, in fit
    'Got array with shape: ' + str(x.shape))
ValueError: Input to `.fit()` should have rank 4. Got array with shape: (1, 250, 250, 3, 1)
```

Did you run into this before?

Could you clarify why you are adding a new axis after the channels and also what gt_gen() is doing? Specifically `y[:,0] = 0.` and `y[:,1] = 1.`

Thanks.

**Comment by aaronphilip** [comment]
The ground truth labels should be grayscale images not RGB. 

The reason for these lines is detailed under Pitfalls - Class Imbalance.
```
y[:,0] = 0
y[:,1] = 1
```

Basically, to use 'class_weight' you need to set the first two elements of each label to `[0,1,...]` so that Keras knows there are only two classes.
