### ISSUE TITLE
What is the size of the label image of your used data set?

### ISSUE THREAD

**Issue by MachineLearning-Nerd** [Aaronphilip2/Image-Segmentation-for-Faces#4]
This seems that you label image is in two dimension: 
mask_datagen.fit(np.expand_dims(np.expand_dims(np.asarray(Image.open(mask_path)), axis=0), axis = 4), augment=True, seed=seed)

But I have seen the LFW part label dataset have a three-dimensional RGB image. 

If you can help me then please help me.

**Comment by aaronphilip** [comment]
The input images are color images while the ground truth labels are grayscale images. In the ground truth labels, white pixels represent where the face is and black pixels are everything else.
